CREATE TABLE FUNCIONARIOS
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(11) NOT NULL,
RG VARCHAR(9) NOT NULL,
EMAIL VARCHAR(120) NOT NULL,
SENHA VARCHAR(32) NOT NULL,
CARGO INT NOT NULL,
ATIVO BIT NOT NULL,
RUA VARCHAR(70) NOT NULL,
BAIRRO VARCHAR(70) NOT NULL,
NUMEROCASA INT NOT NULL,
ISADM BIT NOT NULL,
CONSTRAINT UQ_FUNCIONARIO_EMAIL UNIQUE (EMAIL),
CONSTRAINT UQ_FUNCIONARIO_CPF UNIQUE (CPF),
CONSTRAINT UQ_FUNCIONARIO_RG UNIQUE (RG)
);

CREATE TABLE CLIENTES
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(100) NOT NULL,
CPF VARCHAR(11) NOT NULL,
RG VARCHAR(9) NOT NULL,
TELEFONEFIXO VARCHAR(10) NOT NULL,
TELEFONECELULAR VARCHAR(11) NOT NULL,
EMAIL VARCHAR(120) NOT NULL,
ATIVO BIT NOT NULL,
CONSTRAINT UQ_CLIENTE_EMAIL UNIQUE (EMAIL),
CONSTRAINT UQ_CLEINTE_CPF UNIQUE (CPF),
CONSTRAINT UQ_CLIENTE_RG UNIQUE (RG)
);

CREATE TABLE FORNECEDORES
(
ID INT PRIMARY KEY IDENTITY,
RAZAOSOCIAL VARCHAR(100) NOT NULL,
NOME VARCHAR(100) NOT NULL,
CNPJ VARCHAR(14) NOT NULL,
TELEFONECELULAR VARCHAR(11) NOT NULL,
EMAIL VARCHAR(120) NOT NULL,
ATIVO BIT NOT NULL
CONSTRAINT UQ_FORNECEDOR_EMAIL UNIQUE (EMAIL),
CONSTRAINT UQ_FORNECEDOR_CNPJ UNIQUE (CNPJ),
);

CREATE TABLE PRODUTOS
(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(100) NOT NULL,
DESCRICAO VARCHAR(120) NOT NULL,
VALORUNITARIO FLOAT(53) NULL,
QTDESTOQUE INT NOT NULL
);

CREATE TABLE ENTRADAPRODUTOS
(
ID INT PRIMARY KEY IDENTITY,
DATAENTRADA DATETIME2 DEFAULT GETDATE() NOT NULL,
VALOR FLOAT(53) NOT NULL,
FUNCIONARIOID INT NOT NULL,
FORNECEDORID INT NOT NULL,
CONSTRAINT FK_FUNCIONARIO_RECEBE_PRODUTO FOREIGN KEY (FUNCIONARIOID) REFERENCES FUNCIONARIOS,
CONSTRAINT FK_FORNECEDOR_PRODUTO FOREIGN KEY (FORNECEDORID) REFERENCES FORNECEDORES
);

CREATE TABLE VENDAPRODUTOS
(
ID INT PRIMARY KEY IDENTITY,
DATAVENDA DATETIME2 DEFAULT GETDATE() NOT NULL,
VALOR  FLOAT(53) NOT NULL,
FUNCIONARIOID INT NOT NULL,
CONSTRAINT FK_FUNCIONARIO_VENDE_PRODUTO FOREIGN KEY (FUNCIONARIOID) REFERENCES FUNCIONARIOS
);

CREATE TABLE ITENSENTRADA
(
ID INT PRIMARY KEY IDENTITY,
ENTRADAID INT NOT NULL,
PRODUTOID INT NOT NULL,
VALOR FLOAT(53) NOT NULL,
QUANTIDADE INT NOT NULL,
CONSTRAINT FK_ITEM_ENTRADA FOREIGN KEY (ENTRADAID) REFERENCES ENTRADAPRODUTOS,
CONSTRAINT FK_ENTRADA_PRODUTO FOREIGN KEY (PRODUTOID) REFERENCES PRODUTOS
);

CREATE TABLE ITENSVENDA
(
VENDAID INT NOT NULL,
PRODUTOID INT NOT NULL,
VALOR FLOAT(53) NOT NULL,
QUANTIDADE INT NOT NULL,
CLIENTEID INT NOT NULL,
FOIPAGO INT NOT NULL,
CONSTRAINT FK_ITEM_VENDA FOREIGN KEY (VENDAID) REFERENCES VENDAPRODUTOS,
CONSTRAINT FK_VENDA_PRODUTO FOREIGN KEY (PRODUTOID) REFERENCES PRODUTOS
);

CREATE TABLE QUARTOS
(
ID INT PRIMARY KEY IDENTITY,
TIPOQUARTO INT NOT NULL,
VALORNOITE FLOAT(53) NOT NULL,
PESSOASMAXIMAS INT NOT NULL,
OCUPADO BIT NOT NULL
);

CREATE TABLE CHECKIN
(
ID INT PRIMARY KEY IDENTITY,
QUARTOID INT NOT NULL,
CLIENTEID INT NOT NULL,
DATAENTRADA DATE DEFAULT GETDATE() NOT NULL,
DATASAIDAPREVISTA DATE DEFAULT GETDATE() NOT NULL,
CONSTRAINT FK_QUARTO_CHECKIN FOREIGN KEY (QUARTOID) REFERENCES QUARTOS,
CONSTRAINT FK_CLIENTE_CHECKIN FOREIGN KEY (CLIENTEID) REFERENCES CLIENTES
);

CREATE TABLE CHECKOUT
(
ID INT PRIMARY KEY IDENTITY,
QUARTOID INT NOT NULL,
CLIENTEID INT NOT NULL,
DATASAIDA DATE DEFAULT GETDATE() NOT NULL,
VALOR  FLOAT(53) NOT NULL,
CHECKINID INT NOT NULL,
CONSTRAINT FK_QUARTO_CHECKOUT FOREIGN KEY (QUARTOID) REFERENCES QUARTOS,
CONSTRAINT FK_CLIENTE_CHECKOUT FOREIGN KEY (CLIENTEID) REFERENCES CLIENTES
);

CREATE TABLE LIMPEZAQUARTOS
(
ID INT PRIMARY KEY IDENTITY NOT NULL,
QUARTOID INT NOT NULL,
FUNCIONARIOID INT NOT NULL,
CONSTRAINT FK_QUARTO_EH_LIMPO FOREIGN KEY (QUARTOID) REFERENCES QUARTOS,
CONSTRAINT FK_FUNCIONARIO_LIMPA_QUARTO FOREIGN KEY (FUNCIONARIOID) REFERENCES FUNCIONARIOS
);

INSERT INTO FUNCIONARIOS (NOME, CPF, RG, EMAIL, SENHA, CARGO, ATIVO, RUA, BAIRRO, NUMEROCASA, ISADM)
VALUES ('FUNCIONARIO TESTE DA SILVA', '09835362955', '674404622', 'teste@gmail.com', '123', 0, 1, 'TIRADENTES', 'PROGRESSO', 12, 1);